services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # Prevent overwriting node_modules
    depends_on:
      - redis
      - mysql
    networks:
      - app-net      
    # Use a custom command to wait for the MySQL service to be ready, then push the schema and start the app
    # NOTE: Running in hybrid mode
    command: >
      sh -c "
        until nc -z mysql 3306;
        do
          echo 'Waiting for MySQL...';
          sleep 1;
        done;
        echo 'MySQL is up and running!';

        # Drop the database using Prisma before continuing
        # npx prisma db execute --url '$DATABASE_URL' --script 'DROP DATABASE IF EXISTS \`mydb\`; CREATE DATABASE \`mydb\`;'
        
        # Use db push for development; for production, consider migrate deploy
        npx prisma db push;
        
        npm run dev;
      "
    env_file:
      - .env.docker.dev # Load environment variables from an external file
  redis:
    image: 'redis:latest'
    volumes:
      - redis-data:/data
    networks:
      - app-net      
    expose:
      - '6379'
    ports:
      - '6380:6379'
  mysql:
    image: 'mysql:8.0'
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env.docker.dev
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-net      
    expose:
      - '3306'
    ports:
      - '3307:3306'      
volumes:
  mysql-data:
  redis-data:

networks:
  app-net:
    driver: bridge
    