services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - mysql
    networks:
      - app-net      
    # Use a custom command to wait for the MySQL service to be ready, then push the schema and start the app
    # NOTE: Running in hybrid mode
    command: >
      sh -c "
        until nc -z mysql 3306;
        do
          echo 'Waiting for MySQL...';
          sleep 1;
        done;
        echo 'MySQL is up and running!';
        
        # Use db push for development; for production, consider migrate deploy
        npx prisma db push;
        
        npm run start;
      "
    env_file:
      - .env.docker # Load environment variables from an external file
  redis:
    image: 'redis:latest'
    volumes:
      - redis-data:/data
    networks:
      - app-net
    expose:
      - '6379'
    sysctls:
      vm.overcommit_memory: '1'      
  mysql:
    image: 'mysql:8.0'
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env.docker # Load environment variables from an external file
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-net
    expose:
      - '3306'
volumes:
  mysql-data:
  redis-data:

networks:
  app-net:
    driver: bridge
